### PR TITLE
Fixed non-response of active links in the navbar

### PR DESCRIPTION
**Pull request by madm234**
1. Fixed the issue of unresponsiveness of navbar links.
2. Currently contact link is not linked to any file , therefore as for now I have added javascript code for that which makes it look responsive too. However I have seen there is a contact.html file and I'm sure it will be added in future to that contact link so have also made changes in that file regarding this issue.

image

### CODE REVIEW

**Comment by madm234** [comment]
Kindly make this contribution under Hactoberfest. I'll be very grateful to you.
image

**Comment by madm234** [comment]
@karantec please merge this pr. I'm again requesting.

**Comment by karantec** [comment]
Okay

**Comment by karantec** [comment]
Merged

**Comment by karantec** [comment]
Okay

**Comment by karantec** [comment]
,MERGED

**Pull request merged**
